Assignment5/Pages/CartSummary.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment5.Infrastructure;
using Assignment5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment5.Pages
{
    //Connects to the CartSummary Razor Page
    public class CartSummaryModel : PageModel
    {
        private IBookstoreRepository repository;

        //Constructor to set the repository
        public CartSummaryModel(IBookstoreRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }

        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

        //Set our returnUrl to the one given, or just / if it wasnt given
        //Add the cart to the session when the page is loaded (on Get) using the GetJson method made in the SessionExtentions class
        //Or if there isn't a cart saved, make a new cart
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        //On post, look at repo to find the matching project. Get the cart or make a new one, then add the project to the cart
        //Then set the json to the cart with the updated info
        //The names of the parameters passed in need to be the same as the asp-for values in the cshtml they are being pulled from (not case sensitive)
        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookId == bookId);

            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

            Cart.AddItem(book, 1);

            //HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl }); //The objects returnUrl is set to the returnUrl that was passed in
        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Assignment5/Pages/CartSummary.cshtml
@* Razor Page automatically builds out a model and everything it does is self contained. MVVM (Model, View, View Model) *@
@page
@model Assignment5.Pages.CartSummaryModel
@{
}
<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-left">@line.Book.Title</td>
            <td class="text-center">@line.Quantity</td>
            <td class="text-right">@line.Book.Price</td>
            <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c"))</td>
            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="BookId"
                           value="@line.Book.BookId" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c")</td>
            <td></td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>