Assignment5/Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment5.Models;
using Microsoft.AspNetCore.Mvc;
using Assignment5.Pages;

namespace Assignment5.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Assignment5/Components/NavigationMenuViewComponent.cs
using Assignment5.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment5.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBookstoreRepository repository;

        public NavigationMenuViewComponent(IBookstoreRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()    //Building info for a partial view, but need to build the actual view
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];    //whatever it is called in endpoint routing

            return View(repository.Books.
                Select(x => x.Category).
                Distinct().
                OrderBy(x => x));
        }
    }
}

Assignment5/Views/Shared/BookSummary.cshtml
@*A partial view to see specific books that can be referred to in main views (like Index.cshtml)*@

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>@Model.Title</h4>
        <span class="badge badge-pill badge-primary float-right text-center">
            <p>$@Model.Price</p>
        </span>
        <p>By @Model.AuthorFirstName @Model.AuthorLastName</p>
        <p>Publisher: @Model.Publisher</p>
        <p>Classification: @Model.Classification</p>
        <p>Category: @Model.Category</p>
        <p>Number of Pages: @Model.NumPages</p>
        <p>ISBN: @Model.ISBN</p>
    </div>
    <!--Hidden inputs are to pass information from the view to a class-->
    <form id="@Model.BookId" asp-page="/CartSummary" method="post">
        <input type="hidden" asp-for="BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            <button type="submit" class="btn btn-success btn-sml pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

Assignment5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The BookList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The BookList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row m-1 p-1">
            <div class="col-4" id="hi">
                <vc:navigation-menu />
            </div>
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - The BookList
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
</body>
</html>